# This is a basic workflow to help you get started with Actions

name: Binary Deployment

# Controls when the action will run. 
on:
  push:
    tags:
      - '[v]?[0-9]+.[0-9]+.[0-9]+'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: cancel
    if: github.event_name != 'pull_request' 
    strategy:
      matrix:
        job:
          - name: focal
            distro: focal
            base_image: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
          - name: focal-nogpu
            distro: focal
            base_image: ubuntu:focal
        # - name: bionic
        #   distro: bionic
        #   base_image: nvidia/opengl:1.2-glvnd-runtime-ubuntu18.04
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          file: Dockerfile.binary
          push: true
          tags: lmark1/uav_ros_simulation:${{ matrix.job.name }}-bin-${{ github.ref_name }}
          ssh: |
            default=/tmp/ssh_agent.sock
          build-args: |
            DISTRO=${{ matrix.job.distro }}
            VERSION=${{ github.ref_name }}
            BASE_IMAGE=${{ matrix.job.base_image }}
